(ns mooncake.integration.kerodon-selectors)

(def header-sign-out-link :.func--sign-out__link)
(def header-customise-feed-link :.func--customise-feed__link)
(def feed-page-body :.func--feed-page)
(def feed-page-activity-list :.func--activity-stream)
(def feed-page-activity-item :.func--activity-item)
(def feed-page-activity-item-title :.func--activity-item__title)
(def feed-page-activity-item-author :.func--activity-item__action__author)
(def feed-page-activity-item-action :.func--activity-item__action)
(def feed-page-activity-item-link :.func--activity-item__link)
(def feed-page-no-active-sources-message :.func--empty-activity-item)
(def sign-in-page-body :.func--sign-in-page)
(def sign-in-flash-message :.func--flash-message-container)
(def sign-in-page-sign-in-with-d-cent-link :.func--sign-in-with-d-cent)
(def error-500-page-body :.func--error-500-page)
(def error-404-page-body :.func--error-404-page)
(def create-account-page-body :.func--create-account-page)
(def create-account-page-username-input :.func--username__input)
(def create-account-page-submit-button :.func--create-account__button)
(def customise-feed-page-body :.func--customise-feed-page)
(def customise-feed-page-submit-button :.func--customise-feed__submit)
(def customise-feed-page-feed-item-child-list-item-label :.func--feed-item-child__label)
(def customise-feed-page-feed-item-child-checkbox :.func--feed-item-child__checkbox)
(def newer-activities-link :.func--newer-activities__link)
(def older-activities-link :.func--older-activities__link)
(def untrusted-source-warning-icon :.func--activity-item__suspicious--untrusted-source)
(def unverified-signature-warning-icon :.func--activity-item__suspicious--unverified-signature)

