(ns mooncake.integration.kerodon-selectors)

(def header-sign-out-link :.func--sign-out__link)
(def feed-page-body :.func--feed-page)
(def feed-page-activity-item-title :.func--activity-item__title)
(def feed-page-activity-item-action :.func--activity-item__action)
(def feed-page-activity-item-link :.func--activity-item__link)
(def sign-in-page-body :.func--sign-in-page)
(def sign-in-page-sign-in-with-d-cent-link :.func--sign-in-with-d-cent)
(def error-500-page-body :.func--error-500-page)
(def error-404-page-body :.func--error-404-page)
(def create-account-page-body :.func--create-account-page)
(def create-account-page-username-input :.func--username__input)
(def create-account-page-submit-button :.func--create-account__button)
(def customise-feed-page-body :.func--customise-feed-page)
(def customise-feed-page-feed-item-list-item-label :.func--feed-item__label)
(def customise-feed-page-feed-item-checkbox :.func--feed-item__checkbox)
(def customise-feed-page-submit-button :.func--customise-feed__submit)
